PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX cogs: <http://vocab.deri.ie/cogs#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?job ?op ?st str(?created) as ?since ?timediff str(count(?task)) as ?task_count WHERE {
  ?job a cogs:Job ;
    <http://redpencil.data.gift/vocabularies/tasks/operation> ?operation;
    adms:status ?status;
    dct:created ?created;
    dct:modified ?modified.
  
  ?task dct:isPartOf ?job.
  BIND( REPLACE( str(?operation) , '^.*/', '' ) AS ?op )
  BIND( REPLACE( str(?parent_operation) , '^.*/', '' ) AS ?pop )
  BIND( REPLACE( str(?status) , '^.*/', '' ) AS ?st )
  BIND(str(?modified - ?created) as ?timediff)
}
